name: 'codenotify'
description: 'Notify subscribed users and groups of changes.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
inputs:
  filename: 'Filename to analyze for notifications'
  required: false
  default: 'CODENOTIFY'
