name: 'codenotify'
description: 'Notify subscribed users and groups of changes.'
inputs:
  filename:
    description: 'Filename in which file subscribers are defined'
    required: false
    default: 'CODENOTIFY'
  subscriber_threshold:
    description: 'The threshold of notifying subscribers to prevent broad spamming, 0 to disable'
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
