jobs:
  codenotify:
    runs-on: ubuntu-latest
    name: codenotify 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./ # If you were using this in your project, this would be sourcegraph/codenotify@vX.Y.Z (check releases on GitHub for latest version number)
        env:
          # This token needs to have repo scope and read:org scope (to be able to mention teams).
          GITHUB_TOKEN: ${{ secrets.CODENOTIFY_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: foo
          GIT_AUTHOR_EMAIL: foo@sourcegraph.com
