name: scip-go
"on":
  push:
    paths:
      - '**.go'
      - '**/scip-go.yml'

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read

jobs:
  scip-go:
    if: github.repository == 'sourcegraph/codenotify'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run scip-go and upload
        uses: sourcegraph/scip-go-action@v2
        with:
          sourcegraph-url: https://sourcegraph.sourcegraph.com/
          sourcegraph-token: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}
          scip-go-version: v0.2.2
          upload: true
